name: Salesforce Actions
on:
  pull_request:
    branches:
      - master

jobs:
  run_tests:
    name: Run Apex Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Salesforce CLI
      uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Install Salesforce CLI
      run: |
        npm install -g sfdx-cli

    - name: 'Populate auth file with SFDX_URL secret of integration org'
      shell: bash
      run: |
        echo ${{secrets.SALESFORCE_AUTH_URL}} | sed 's/./& /g'
        echo ${{ secrets.SALESFORCE_AUTH_URL}} > ./SALESFORCE_AUTH_URL.txt

    # Authenticate to org using the URL stored in the text file
    - name: 'Authenticate to Integration Org'
      run: sfdx auth:sfdxurl:store -f ./SALESFORCE_AUTH_URL.txt -s -a integration
  
    - name: Run Apex PMD
      run: |
        sfdx force:apex:pmd:violations --format xml --outputfile pmd-report.xml
        
    - name: Generate Code Coverage Report
      run: |
        sfdx force:apex:test:run --codecoverage --resultformat junit --outputdir test-results
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test-results/
